### ISSUE TITLE
Questions about the adaptation phase.

### ISSUE THREAD

**Issue by zafarali** [ramanans1/plan2explore#6]
Hi Ramanan,
Thanks for the nice paper and open sourced code! I had a few questions about the adaptation phase:

- Where does the reward function come for the adaptation phase? (in particular I am looking for Step 7 of Algorithm 2) From my understanding this line: https://github.com/ramanans1/plan2explore/blob/887a3ac70d1ff08ab292911a74064ca1ac5512e6/plan2explore/training/utility.py#L297 shows that Step 7 is being trained simultaneously with Algorithm 1. If true, won't this affect what we see in Figure 3 since that reward function is not completely trained until later? Does this also mean that graph.heads.reward is trained for the extrinsic task?  Which head uses the intrinsic rewards?
~How do we prevent leakage of the reward of the downstream task to the agent?~ I see there is a `stop_gradient` if `config.adaptation` is `False` so there should be no leakage.

- I assume that `graph.heads.action` is the exploration policy and is independent of `graph.heads.action_target` which is the target task policy. In this line https://github.com/ramanans1/plan2explore/blob/887a3ac70d1ff08ab292911a74064ca1ac5512e6/plan2explore/training/utility.py#L240 the objective for `graph.heads.action` and is computed from the `raw_features` which uses `graph.heads.reward`. How is the adaptation phase used? i.e. where is the resetting of the action head happen. The paper mentions that `Throughout the exploration, we take snapshots of the agent to train a task policy on the final task and plot its zero-shot performance.` and it is not clear to me where this step is being implemented.

Can you clarify how to correctly read the code?

**Comment by orybkin** [comment]
Hi Zafarali,

This is correct, the stop gradient prevents the leakage. The exploration policy and the model are trained without any task knowledge. However, to perform the downstream task, we train a reward predictor on the collected data. In this implementation, since we are testing on standard DM control tasks, we know the task from the beginning, so we simply train the reward predictor in parallel with exploration, but it is separate from the model and doesn't affect it. You could equivalently train the reward predictor afterwards and get the same results.

For your second question, in this implementation, the downstream policy learning is again done in parallel to exploration to speed up training (so that we don't have to train one policy first and then the other policy after that). Again, this does not impact the model training and you could equivalently train the downstream policy after the model has converged.

**Comment by zafarali** [comment]
Thanks for the response!

With regards to:

> For your second question, in this implementation, the downstream policy learning is again done in parallel to exploration to speed up training (so that we don't have to train one policy first and then the other policy after that).

Does this mean that for every evaluation on the curve the target policy agent and the reward function is trained for a different amount of time?
i.e. the curve at T = 10 is trained using all data T < 10 and is trained for 10x longer than the curve at T=1?

Thanks

**Comment by orybkin** [comment]
Yes, that's right. You can reproduce the curve by running the code and checking the task policy performance. You are right that you could get better results by training task policy to convergence each time instead, however, that would make producing the graph very expensive. If you are interested in practical performance, you would first train the exploration policy + model until convergence, then specify the task, and then train the task policy until convergence. This should be easy to add to the released implementation.

**Comment by zafarali** [comment]
Thanks for clarifying!
